#!/usr/bin/env python

from flask.ext.script import Manager, Server
from initializer import app

manager = Manager(app)

@manager.command
def run():
    app.run()


if __name__ == '__main__':
    manager.run()
