#!/usr/bin/env python

from flask.ext.script import Manager, Server
from initializer import app
from initializer import database

manager = Manager(app)

@manager.command
@manager.option('-r', '--recreate', dest='recreate', action='store_true')
@manager.option('-d', '--debug', dest='debug', action='store_true')
def run(recreate=False, debug=False):

    if recreate:
        recreate_database()

    app.run(debug=debug)

def recreate_database():
    print('Droping database schema...')
    database.drop_all()

    print('Creating database schema...')
    database.create_all()

    print('Database schema recreated.')


if __name__ == '__main__':
    manager.run()
